#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Finance-Bank-LaPoste
version:      0.01
version_from: lib/Finance/Bank/LaPoste.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
