--- #YAML:1.0
name:                Finance-Bank-LaPoste
version:             5.00
abstract:             Check your "La Poste" accounts from Perl
license:             ~
author:              
    - Pixel <pixel@rigaux.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
